"""
Cloud component definitions for AWS, Azure, GCP, and OpenStack.
Each component has: id, label, icon (emoji), category, provider, description, config_defaults
"""

CLOUD_COMPONENTS = {
    "aws": {
        "compute": [
            {"id": "aws_ec2", "label": "EC2 Instance", "icon": "🖥️", "category": "Compute",
             "description": "Virtual machine in AWS", "color": "#FF9900",
             "config": {"instance_type": "t3.micro", "ami": "ami-0c55b159cbfafe1f0", "key_name": ""}},
            {"id": "aws_lambda", "label": "Lambda", "icon": "λ", "category": "Compute",
             "description": "Serverless function", "color": "#FF9900",
             "config": {"runtime": "python3.11", "memory": 128, "timeout": 30}},
            {"id": "aws_ecs", "label": "ECS Cluster", "icon": "🐳", "category": "Compute",
             "description": "Container orchestration", "color": "#FF9900",
             "config": {"capacity_providers": ["FARGATE"]}},
            {"id": "aws_eks", "label": "EKS Cluster", "icon": "⚓", "category": "Compute",
             "description": "Managed Kubernetes", "color": "#FF9900",
             "config": {"k8s_version": "1.29", "node_instance_type": "m5.large"}},
            {"id": "aws_autoscaling", "label": "Auto Scaling", "icon": "↕️", "category": "Compute",
             "description": "Auto Scaling Group", "color": "#FF9900",
             "config": {"min_size": 1, "max_size": 5, "desired": 2}},
        ],
        "networking": [
            {"id": "aws_vpc", "label": "VPC", "icon": "🔲", "category": "Networking",
             "description": "Virtual Private Cloud", "color": "#8C4FFF",
             "config": {"cidr": "10.0.0.0/16", "enable_dns": True}},
            {"id": "aws_subnet", "label": "Subnet", "icon": "📋", "category": "Networking",
             "description": "VPC Subnet", "color": "#8C4FFF",
             "config": {"cidr": "10.0.1.0/24", "availability_zone": "us-east-1a"}},
            {"id": "aws_alb", "label": "Load Balancer", "icon": "⚖️", "category": "Networking",
             "description": "Application Load Balancer", "color": "#8C4FFF",
             "config": {"scheme": "internet-facing", "type": "application"}},
            {"id": "aws_cloudfront", "label": "CloudFront", "icon": "🌐", "category": "Networking",
             "description": "CDN Distribution", "color": "#8C4FFF",
             "config": {"price_class": "PriceClass_100"}},
            {"id": "aws_route53", "label": "Route 53", "icon": "🗺️", "category": "Networking",
             "description": "DNS Service", "color": "#8C4FFF",
             "config": {"type": "A", "ttl": 300}},
            {"id": "aws_apigateway", "label": "API Gateway", "icon": "🚪", "category": "Networking",
             "description": "REST/HTTP API Gateway", "color": "#8C4FFF",
             "config": {"type": "REST", "stage": "prod"}},
            {"id": "aws_sg", "label": "Security Group", "icon": "🛡️", "category": "Networking",
             "description": "Firewall rules", "color": "#8C4FFF",
             "config": {"ingress_port": 443, "protocol": "tcp"}},
        ],
        "storage": [
            {"id": "aws_s3", "label": "S3 Bucket", "icon": "🪣", "category": "Storage",
             "description": "Object storage", "color": "#3F8624",
             "config": {"versioning": True, "encryption": "AES256"}},
            {"id": "aws_ebs", "label": "EBS Volume", "icon": "💾", "category": "Storage",
             "description": "Block storage", "color": "#3F8624",
             "config": {"size": 20, "type": "gp3"}},
            {"id": "aws_efs", "label": "EFS", "icon": "📁", "category": "Storage",
             "description": "Elastic File System", "color": "#3F8624",
             "config": {"performance_mode": "generalPurpose"}},
        ],
        "database": [
            {"id": "aws_rds", "label": "RDS", "icon": "🗄️", "category": "Database",
             "description": "Managed relational DB", "color": "#1A476F",
             "config": {"engine": "postgres", "instance_class": "db.t3.micro", "allocated_storage": 20}},
            {"id": "aws_dynamodb", "label": "DynamoDB", "icon": "⚡", "category": "Database",
             "description": "NoSQL database", "color": "#1A476F",
             "config": {"billing_mode": "PAY_PER_REQUEST", "hash_key": "id"}},
            {"id": "aws_elasticache", "label": "ElastiCache", "icon": "🏎️", "category": "Database",
             "description": "In-memory cache", "color": "#1A476F",
             "config": {"engine": "redis", "node_type": "cache.t3.micro"}},
            {"id": "aws_aurora", "label": "Aurora", "icon": "🌟", "category": "Database",
             "description": "Aurora MySQL/Postgres", "color": "#1A476F",
             "config": {"engine": "aurora-postgresql", "instance_class": "db.t3.medium"}},
        ],
        "security": [
            {"id": "aws_iam_role", "label": "IAM Role", "icon": "👤", "category": "Security",
             "description": "Identity & Access role", "color": "#DD344C",
             "config": {"assume_role_service": "ec2.amazonaws.com"}},
            {"id": "aws_kms", "label": "KMS Key", "icon": "🔑", "category": "Security",
             "description": "Key Management Service", "color": "#DD344C",
             "config": {"deletion_window": 10, "enable_rotation": True}},
            {"id": "aws_waf", "label": "WAF", "icon": "🔒", "category": "Security",
             "description": "Web Application Firewall", "color": "#DD344C",
             "config": {"scope": "REGIONAL"}},
        ],
        "messaging": [
            {"id": "aws_sqs", "label": "SQS Queue", "icon": "📨", "category": "Messaging",
             "description": "Simple Queue Service", "color": "#E7157B",
             "config": {"message_retention": 345600, "visibility_timeout": 30}},
            {"id": "aws_sns", "label": "SNS Topic", "icon": "📢", "category": "Messaging",
             "description": "Notification Service", "color": "#E7157B",
             "config": {"protocol": "email"}},
            {"id": "aws_eventbridge", "label": "EventBridge", "icon": "🎯", "category": "Messaging",
             "description": "Event bus", "color": "#E7157B",
             "config": {"schedule": "rate(5 minutes)"}},
        ],
        "monitoring": [
            {"id": "aws_cloudwatch", "label": "CloudWatch", "icon": "📊", "category": "Monitoring",
             "description": "Monitoring & logging", "color": "#759C3E",
             "config": {"retention_days": 30}},
            {"id": "aws_xray", "label": "X-Ray", "icon": "🔍", "category": "Monitoring",
             "description": "Distributed tracing", "color": "#759C3E",
             "config": {}},
        ],
    },
    "azure": {
        "compute": [
            {"id": "azurerm_virtual_machine", "label": "Virtual Machine", "icon": "🖥️", "category": "Compute",
             "description": "Azure VM", "color": "#0078D4",
             "config": {"vm_size": "Standard_B2s", "os": "Ubuntu"}},
            {"id": "azurerm_function_app", "label": "Function App", "icon": "λ", "category": "Compute",
             "description": "Serverless functions", "color": "#0078D4",
             "config": {"runtime": "python", "version": "3.11"}},
            {"id": "azurerm_aks_cluster", "label": "AKS Cluster", "icon": "⚓", "category": "Compute",
             "description": "Azure Kubernetes Service", "color": "#0078D4",
             "config": {"k8s_version": "1.29", "node_vm_size": "Standard_D2s_v3"}},
            {"id": "azurerm_app_service", "label": "App Service", "icon": "🌐", "category": "Compute",
             "description": "Web app hosting", "color": "#0078D4",
             "config": {"sku": "P1v3", "os_type": "Linux"}},
            {"id": "azurerm_container_instance", "label": "Container Instance", "icon": "🐳", "category": "Compute",
             "description": "Serverless containers", "color": "#0078D4",
             "config": {"cpu": 1, "memory": 1.5}},
        ],
        "networking": [
            {"id": "azurerm_virtual_network", "label": "Virtual Network", "icon": "🔲", "category": "Networking",
             "description": "Azure VNet", "color": "#773ADC",
             "config": {"address_space": "10.0.0.0/16"}},
            {"id": "azurerm_subnet", "label": "Subnet", "icon": "📋", "category": "Networking",
             "description": "VNet Subnet", "color": "#773ADC",
             "config": {"address_prefix": "10.0.1.0/24"}},
            {"id": "azurerm_load_balancer", "label": "Load Balancer", "icon": "⚖️", "category": "Networking",
             "description": "Azure LB", "color": "#773ADC",
             "config": {"sku": "Standard"}},
            {"id": "azurerm_application_gateway", "label": "App Gateway", "icon": "🚪", "category": "Networking",
             "description": "L7 load balancer + WAF", "color": "#773ADC",
             "config": {"sku_tier": "WAF_v2"}},
            {"id": "azurerm_dns_zone", "label": "DNS Zone", "icon": "🗺️", "category": "Networking",
             "description": "Azure DNS", "color": "#773ADC",
             "config": {}},
            {"id": "azurerm_network_security_group", "label": "NSG", "icon": "🛡️", "category": "Networking",
             "description": "Network Security Group", "color": "#773ADC",
             "config": {"rule_priority": 100}},
        ],
        "storage": [
            {"id": "azurerm_storage_account", "label": "Storage Account", "icon": "🪣", "category": "Storage",
             "description": "Blob/File/Queue/Table storage", "color": "#107C10",
             "config": {"account_tier": "Standard", "replication": "LRS"}},
            {"id": "azurerm_managed_disk", "label": "Managed Disk", "icon": "💾", "category": "Storage",
             "description": "Persistent block storage", "color": "#107C10",
             "config": {"disk_size_gb": 128, "sku": "Premium_LRS"}},
        ],
        "database": [
            {"id": "azurerm_postgresql_server", "label": "PostgreSQL", "icon": "🐘", "category": "Database",
             "description": "Managed PostgreSQL", "color": "#1A476F",
             "config": {"sku_name": "GP_Gen5_2", "version": "14"}},
            {"id": "azurerm_cosmosdb_account", "label": "Cosmos DB", "icon": "🌌", "category": "Database",
             "description": "Multi-model NoSQL DB", "color": "#1A476F",
             "config": {"consistency": "Session", "offer_type": "Standard"}},
            {"id": "azurerm_redis_cache", "label": "Redis Cache", "icon": "🏎️", "category": "Database",
             "description": "Managed Redis", "color": "#1A476F",
             "config": {"sku_name": "Basic", "family": "C", "capacity": 1}},
            {"id": "azurerm_sql_server", "label": "SQL Database", "icon": "🗄️", "category": "Database",
             "description": "Azure SQL", "color": "#1A476F",
             "config": {"version": "12.0", "sku": "S1"}},
        ],
        "security": [
            {"id": "azurerm_key_vault", "label": "Key Vault", "icon": "🔑", "category": "Security",
             "description": "Secrets & keys management", "color": "#DD344C",
             "config": {"sku_name": "standard"}},
            {"id": "azurerm_user_assigned_identity", "label": "Managed Identity", "icon": "👤", "category": "Security",
             "description": "Azure managed identity", "color": "#DD344C",
             "config": {}},
        ],
        "messaging": [
            {"id": "azurerm_servicebus_namespace", "label": "Service Bus", "icon": "📨", "category": "Messaging",
             "description": "Enterprise messaging", "color": "#E7157B",
             "config": {"sku": "Standard"}},
            {"id": "azurerm_eventhub_namespace", "label": "Event Hub", "icon": "📢", "category": "Messaging",
             "description": "Event streaming", "color": "#E7157B",
             "config": {"sku": "Standard", "capacity": 1}},
        ],
        "monitoring": [
            {"id": "azurerm_log_analytics_workspace", "label": "Log Analytics", "icon": "📊", "category": "Monitoring",
             "description": "Log aggregation & analysis", "color": "#759C3E",
             "config": {"retention_days": 30}},
            {"id": "azurerm_application_insights", "label": "App Insights", "icon": "🔍", "category": "Monitoring",
             "description": "APM & telemetry", "color": "#759C3E",
             "config": {"application_type": "web"}},
        ],
    },
    "gcp": {
        "compute": [
            {"id": "google_compute_instance", "label": "Compute Engine", "icon": "🖥️", "category": "Compute",
             "description": "GCP VM instance", "color": "#4285F4",
             "config": {"machine_type": "e2-medium", "zone": "us-central1-a"}},
            {"id": "google_cloudfunctions_function", "label": "Cloud Function", "icon": "λ", "category": "Compute",
             "description": "Serverless function", "color": "#4285F4",
             "config": {"runtime": "python311", "trigger": "http"}},
            {"id": "google_container_cluster", "label": "GKE Cluster", "icon": "⚓", "category": "Compute",
             "description": "Google Kubernetes Engine", "color": "#4285F4",
             "config": {"location": "us-central1", "node_count": 3}},
            {"id": "google_cloud_run_service", "label": "Cloud Run", "icon": "🏃", "category": "Compute",
             "description": "Serverless containers", "color": "#4285F4",
             "config": {"max_instances": 10, "cpu": "1000m"}},
            {"id": "google_app_engine_application", "label": "App Engine", "icon": "🌐", "category": "Compute",
             "description": "Managed app platform", "color": "#4285F4",
             "config": {"location": "us-central"}},
        ],
        "networking": [
            {"id": "google_compute_network", "label": "VPC Network", "icon": "🔲", "category": "Networking",
             "description": "GCP VPC", "color": "#34A853",
             "config": {"auto_create_subnetworks": False}},
            {"id": "google_compute_subnetwork", "label": "Subnetwork", "icon": "📋", "category": "Networking",
             "description": "VPC Subnet", "color": "#34A853",
             "config": {"ip_cidr_range": "10.0.1.0/24", "region": "us-central1"}},
            {"id": "google_compute_forwarding_rule", "label": "Load Balancer", "icon": "⚖️", "category": "Networking",
             "description": "Cloud Load Balancing", "color": "#34A853",
             "config": {"load_balancing_scheme": "EXTERNAL"}},
            {"id": "google_dns_managed_zone", "label": "Cloud DNS", "icon": "🗺️", "category": "Networking",
             "description": "Managed DNS zones", "color": "#34A853",
             "config": {"visibility": "public"}},
            {"id": "google_compute_firewall", "label": "Firewall Rule", "icon": "🛡️", "category": "Networking",
             "description": "VPC firewall rules", "color": "#34A853",
             "config": {"direction": "INGRESS", "allow_protocol": "tcp"}},
        ],
        "storage": [
            {"id": "google_storage_bucket", "label": "Cloud Storage", "icon": "🪣", "category": "Storage",
             "description": "Object storage", "color": "#FBBC04",
             "config": {"location": "US", "storage_class": "STANDARD"}},
            {"id": "google_filestore_instance", "label": "Filestore", "icon": "📁", "category": "Storage",
             "description": "Managed file storage", "color": "#FBBC04",
             "config": {"tier": "STANDARD", "capacity_gb": 1024}},
        ],
        "database": [
            {"id": "google_sql_database_instance", "label": "Cloud SQL", "icon": "🗄️", "category": "Database",
             "description": "Managed relational DB", "color": "#EA4335",
             "config": {"database_version": "POSTGRES_15", "tier": "db-f1-micro"}},
            {"id": "google_firestore_document", "label": "Firestore", "icon": "🔥", "category": "Database",
             "description": "NoSQL document DB", "color": "#EA4335",
             "config": {}},
            {"id": "google_bigtable_instance", "label": "Bigtable", "icon": "📊", "category": "Database",
             "description": "Wide-column NoSQL", "color": "#EA4335",
             "config": {"instance_type": "DEVELOPMENT"}},
            {"id": "google_redis_instance", "label": "Memorystore", "icon": "🏎️", "category": "Database",
             "description": "Managed Redis/Memcached", "color": "#EA4335",
             "config": {"memory_size_gb": 1, "redis_version": "REDIS_7_0"}},
        ],
        "security": [
            {"id": "google_service_account", "label": "Service Account", "icon": "👤", "category": "Security",
             "description": "GCP identity", "color": "#DD344C",
             "config": {}},
            {"id": "google_kms_key_ring", "label": "Cloud KMS", "icon": "🔑", "category": "Security",
             "description": "Key management", "color": "#DD344C",
             "config": {"location": "global"}},
        ],
        "messaging": [
            {"id": "google_pubsub_topic", "label": "Pub/Sub", "icon": "📨", "category": "Messaging",
             "description": "Messaging & streaming", "color": "#E7157B",
             "config": {"message_retention": "86400s"}},
            {"id": "google_cloud_tasks_queue", "label": "Cloud Tasks", "icon": "📋", "category": "Messaging",
             "description": "Distributed task queues", "color": "#E7157B",
             "config": {"max_attempts": 3}},
        ],
        "monitoring": [
            {"id": "google_monitoring_dashboard", "label": "Cloud Monitoring", "icon": "📊", "category": "Monitoring",
             "description": "Metrics & alerting", "color": "#759C3E",
             "config": {}},
            {"id": "google_logging_sink", "label": "Cloud Logging", "icon": "🔍", "category": "Monitoring",
             "description": "Log routing & storage", "color": "#759C3E",
             "config": {}},
        ],
    },
    "openstack": {
        "compute": [
            {"id": "openstack_compute_instance_v2", "label": "Nova Instance", "icon": "🖥️", "category": "Compute",
             "description": "OpenStack VM", "color": "#ED1944",
             "config": {"flavor_name": "m1.small", "image_name": "Ubuntu-22.04"}},
            {"id": "openstack_containerinfra_cluster_v1", "label": "Magnum Cluster", "icon": "⚓", "category": "Compute",
             "description": "K8s via Magnum", "color": "#ED1944",
             "config": {"cluster_template": "k8s-template", "node_count": 3}},
        ],
        "networking": [
            {"id": "openstack_networking_network_v2", "label": "Neutron Network", "icon": "🔲", "category": "Networking",
             "description": "Virtual network", "color": "#6A1B9A",
             "config": {"admin_state_up": True}},
            {"id": "openstack_networking_subnet_v2", "label": "Subnet", "icon": "📋", "category": "Networking",
             "description": "Network subnet", "color": "#6A1B9A",
             "config": {"cidr": "192.168.1.0/24", "ip_version": 4}},
            {"id": "openstack_lb_loadbalancer_v2", "label": "Octavia LB", "icon": "⚖️", "category": "Networking",
             "description": "Load balancer", "color": "#6A1B9A",
             "config": {}},
            {"id": "openstack_networking_router_v2", "label": "Router", "icon": "🌐", "category": "Networking",
             "description": "Neutron router", "color": "#6A1B9A",
             "config": {}},
            {"id": "openstack_networking_secgroup_v2", "label": "Security Group", "icon": "🛡️", "category": "Networking",
             "description": "Security rules", "color": "#6A1B9A",
             "config": {}},
            {"id": "openstack_networking_floatingip_v2", "label": "Floating IP", "icon": "🗺️", "category": "Networking",
             "description": "External IP", "color": "#6A1B9A",
             "config": {}},
        ],
        "storage": [
            {"id": "openstack_blockstorage_volume_v3", "label": "Cinder Volume", "icon": "💾", "category": "Storage",
             "description": "Block storage", "color": "#1B5E20",
             "config": {"size": 50, "volume_type": "ceph"}},
            {"id": "openstack_objectstorage_container_v1", "label": "Swift Container", "icon": "🪣", "category": "Storage",
             "description": "Object storage", "color": "#1B5E20",
             "config": {}},
        ],
        "database": [
            {"id": "openstack_db_instance_v1", "label": "Trove DB", "icon": "🗄️", "category": "Database",
             "description": "DBaaS via Trove", "color": "#1A476F",
             "config": {"datastore": "postgresql", "flavor_id": "d2"}},
        ],
        "security": [
            {"id": "openstack_identity_role_v3", "label": "Keystone Role", "icon": "👤", "category": "Security",
             "description": "Identity role", "color": "#DD344C",
             "config": {}},
        ],
        "messaging": [
            {"id": "openstack_messaging_claim_v2", "label": "Zaqar Queue", "icon": "📨", "category": "Messaging",
             "description": "Message queue", "color": "#E7157B",
             "config": {}},
        ],
        "monitoring": [
            {"id": "openstack_aodh_alarm_v2", "label": "Aodh Alarm", "icon": "📊", "category": "Monitoring",
             "description": "Telemetry alarms", "color": "#759C3E",
             "config": {}},
        ],
    }
}

def get_all_components(provider: str) -> list:
    """Get flat list of all components for a provider."""
    components = []
    for category, items in CLOUD_COMPONENTS.get(provider, {}).items():
        for item in items:
            item["provider"] = provider
            components.append(item)
    return components

def get_component_by_id(component_id: str, provider: str) -> dict:
    """Find a component definition by its ID."""
    for category, items in CLOUD_COMPONENTS.get(provider, {}).items():
        for item in items:
            if item["id"] == component_id:
                item["provider"] = provider
                return item
    return {}
